name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Test shell compatibility
      run: |
        # Verify scripts work with sh
        sh -n ./aifixer.sh
        sh -n ./install.sh
        sh -n ./test_aifixer.sh
    
    - name: Install aifixer
      run: |
        sudo sh ./install.sh --prefix /usr/local --skip-api-key
        
        # Verify installation
        which aifixer
        aifixer --version
        aifixer --help
    
    - name: Run tests
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: |
        chmod +x ./test_aifixer.sh
        sh ./test_aifixer.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Shellcheck
      run: |
        sudo apt-get update && sudo apt-get install -y shellcheck
        shellcheck -s sh ./aifixer.sh || true
        shellcheck -s sh ./install.sh || true
        shellcheck -s sh ./test_aifixer.sh || true
